### PR TITLE
add an argument to split train/val/test data in the set matching task…

### PR DESCRIPTION
**Pull request by wildsnowman**
… from iqon_outfits.json

### CODE REVIEW

**Comment by wildsnowman** [comment]
@nocotan I have added an argument for switching trainval splits in set matching tasks.
Could you check it?

**Comment by nocotan** [comment]
@wildsnowman 
Why is the split argument limited to [0,1,2]?

- benchmarks/set_matching_pytorch/test.py
```python
parser.add_argument("--split", type=int, choices=[0, 1, 2])
```

**Comment by wildsnowman** [comment]
@nocotan 
I'm planning to have experiments using those three splits, and thus reproducing results requires only [0, 1, 2].
Do you want a free splitting?

**Comment by nocotan** [comment]
@wildsnowman OK. My curiosity was clarified.

**Review by nocotan — APPROVED** [review]

**Pull request merged**
